language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rezacse08/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rezacse08/docker-react npm run test
